import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ReactQueryProvider from "./context/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import GoogleMapsContextProvider from "./context/googleMaps";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <GoogleMapsContextProvider>
            {children}
            <Toaster />
          </GoogleMapsContextProvider>
          <ReactQueryDevtools />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
